import sqlite3
conn=sqlite3.connect("database.db")
conn.execute("""
    CREATE TABLE PROFILES
    (USERNAME VARCHAR PRIMARY KEY NOT NULL,
    COUNTRY TEXT,
    STATE TEXT,
    CITY TEXT,
    INSTITUTION TEXT,
    PROFESSION TEXT)
    """)
conn.execute("""
	CREATE TABLE RATINGS
	(USERNAME VARCHAR PRIMARY KEY NOT NULL,
	HIGHESTRATING VARCHAR,
	CURRENTRATING TEXT,
	LONGCHALLENGERATING TEXT,
	COOKOFFRATING TEXT,
	LUNCHTIMERATING TEXT 
	)""")
conn.execute("""
	CREATE TABLE RECENTACTIVITY
	(USERNAME VARCHAR PRIMARY KEY NOT NULL,
	INSTANT DATETIME,
	PROBLEM VARCHAR,
	RESULT VARCHAR,
	LANGUAGE VARCHAR)""")

print("Table Created!!!")
conn.close()
